import 'package:flutter/material.dart';

const Map<String, String> kEmojiByCategory = {
  'beauty': '💄',
  'fragrances': '🌸',
  'furniture': '🛋️',
  'groceries': '🛒',
  'home-decoration': '🎁',
  'kitchen-accessories': '🍳',
  'laptops': '💻',
  'mens-shirts': '👕',
  'mens-shoes': '👟',
  'mens-watches': '⌚',
  'mobile-accessories': '🎧',
  'motorcycle': '🏍️',
  'skin-care': '🧴',
  'smartphones': '📱',
  'sports-accessories': '🏀',
  'sunglasses': '🕶️',
  'tablets': '📲',
  'tops': '👚',
  'vehicle': '🚗',
  'womens-bags': '👜',
  'womens-dresses': '👗',
  'womens-jewellery': '💍',
  'womens-shoes': '👠',
  'womens-watches': '⌚',
};

const Map<String, IconData> kIconsByCategory = {
  'beauty': Icons.face_2_outlined,
  'fragrances': Icons.spa_outlined,
  'furniture': Icons.chair_alt_outlined,
  'groceries': Icons.local_grocery_store_outlined,
  'home-decoration': Icons.home_outlined,
  'kitchen-accessories': Icons.kitchen_outlined,
  'laptops': Icons.laptop_mac_outlined,
  'mens-shirts': Icons.checkroom_outlined,
  'mens-shoes': Icons.directions_run_outlined,
  'mens-watches': Icons.watch_outlined,
  'mobile-accessories': Icons.headphones_outlined,
  'motorcycle': Icons.two_wheeler_outlined,
  'skin-care': Icons.health_and_safety_outlined,
  'smartphones': Icons.smartphone_outlined,
  'sports-accessories': Icons.sports_basketball_outlined,
  'sunglasses': Icons.wb_sunny_outlined,
  'tablets': Icons.tablet_mac_outlined,
  'tops': Icons.style_outlined,
  'vehicle': Icons.directions_car_filled_outlined,
  'womens-bags': Icons.shopping_bag_outlined,
  'womens-dresses': Icons.checkroom_outlined,
  'womens-jewellery': Icons.diamond_outlined,
  'womens-shoes': Icons.shopping_bag_outlined,
  'womens-watches': Icons.watch_outlined,
};
